### ISSUE TITLE
Non ascii path characters lead to exception

### ISSUE THREAD

**Issue by jhildenbrand-festo** [Festo-se/festo-cpx-io#32]
***In GitLab by @elrosch on Oct 22, 2024, 07:52 UTC:***

```
Traceback (most recent call last):
  File "C:\Users\NiklasKreidenweiß\Desktop\output_cntrl_cpx_apa.py", line 83, in <module>
    cpx_apa = CpxAp(ip_address=CPX_IP, timeout=0)
  File "C:\Users\NiklasKreidenweiß\AppData\Local\Programs\Python\Python313\Lib\site-packages\cpx_io\cpx_system\cpx_ap\cpx_ap.py", line 144, in __init__
    generate_system_information_file(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\NiklasKreidenweiß\AppData\Local\Programs\Python\Python313\Lib\site-packages\cpx_io\cpx_system\cpx_ap\ap_docu_generator.py", line 136, in generate_system_information_file
    f.write(
    ~~~~~~~^
        "Documentation of your AP system that is autogenerated by reading "
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        f"your operating system *{ap_system.docu_path}*\n"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 317: ordinal not in range(128)
```

*Migrated from GitLab: https://gitlab.com/festo-research/electric-automation/festo-cpx-io/-/issues/32*

**Comment by jhildenbrand-festo** [comment]
***In GitLab by @elrosch on Oct 22, 2024, 08:08 UTC:***

created branch [`32-non-ascii-path-characters-lead-to-exception`](/festo-research/electric-automation/festo-cpx-io/-/compare/main...32-non-ascii-path-characters-lead-to-exception) to address this issue
